version: '3'
services: 
    python:
        # image: python
        build: 
            context: .
            dockerfile: "./docker/prod/python/DockerFile"
        volumes:
            - ./app:/app
        # command: python manage.py runserver 0.0.0.0:8000
        ports: 
            - "8000:8000"

        command: gunicorn -w 4 app.wsgi -b 0.0.0.0:8000
        
    postgres:
        image: postgres
        ports: 
            - "5432:5432"
        environment: 
            POSTGRES_PASSWORD: postgres_django
            POSTGRES_USER: postgres_user
            POSTGRES_DB: postgres_db

    nginx:
        build:
            context: .
            dockerfile: ./docker/prod/nginx/DockerFile
        ports:
            - "8080:80"